language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements-dev.txt
script:
  - isort -c
  - pytest
deploy:
  provider: pypi
  user: "10349hndsmfa90sdhfbn230"
  password:
    secure: "STUuM7FKhSIZlh38WTZAwpRd9n9d0zEH2SoaoGEdFSO3aSu+5ZqJjOVRj+ApKD0EpWxk46V5IQUqbg6x+NLKtXyFSprlwUTj6BRbs5MpApiayBZ1ifaLixcdjBQvAQeYp3UgFzCs7RZs83AK87IsVhwh5X9d2zwj8yioIO91Cs62vme5MM26171XO+JBwp3kotZy9rRnjOci6FoxS5+O0yVFeRWs/Zp8nO4Rx7AeLMsTzwdI9Yj2XoFMid7vTLR/q783GEG0ObuH3rDMu6pjMbPMmf0hazTRJ9izmkiYsZbOfjQ+ozBa2LhKUcZxr4oD0buCu6+F/n37ZkoBLCLDh8syj5bVYMmA1izLL2xcMeuGIZ1zEXntt8WmE769GbKVwD9HvqhqOkkQ2XfVszT6iSD8xqw9q54DlqKPVYzlsCa7EV+nQ4La4AdmZBiZrkHMdsKwC3l7mCXDpr899m39SLGT3/0gCU8L/efoBoNNlVoBfq9j+hBuo35QWIv2iyT4XkwAzRdDqM56uHUUQDF3migV2XzfqjOqFuek1QpWFSoPGMYS+36IhhVvSNmZi3Fmc5bTCbk1sdhdzFAHqgWRxsqrAC9YR0jIOKE7EFCqk0VFwSU/VsBRHXgiXzS/1sY1ZVi/2S0wDFRAcBNYo0lDQQJMwa8sErlW+TxyNVpVe1s="
  on:
    all_branches: true
    distributions: sdist bdist_wheel
    repo: sgaynetdinov/py-vkontakte
    skip_cleanup: true
