language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements-dev.txt
script:
  - isort -c
  - pytest
deploy:
  provider: pypi
  user: 10349hndsmfa90sdhfbn230
  password:
    secure: FNkN7olKJ2OSGGOCDfX/LZuEvLlJNTDiq7g1Gf08b6EtJDU01OkFLCasv364SWcMKXXlGdQJhTGkp0Ytj0jPaSUG6cvl8mG7eb0HnbdRWksmvj3FIiKUWApWHkRRGg8B+IJHzM5Tkgk/fp7neFqVZQSsLp1WUeXG4SRZmKwNC9Qk/J0GPcyfsGOxyH3l0AtCKPQy/bFVrOnb9zb9NnDlGle3vZw4q1SHBR2Jou/dS2Q2mO1ut/zNixsOqnWIOv1tVjhY6hE4afBNz9v/F8f5yBczbR4CTaPUXzWJ6O3quAJPwfDyqi2CRO90uL8FD4vHr79YDmbKe0GFWoXFgZVnQ5v35uW0fv9eGubkxVrXoO1Yrd1IRKnkRZlGjGMgRbw3rTfhaHuJtFCyYuSSom9Bd1s3aZ3NrnY2+EdMYzosn9WENEI09ZMymin5pC/MkuzgFq9d9nBg4bYcTSBXkewmd86A7np9rpMkTleE8kfoouEvlM1OxJwBJoOOnLMjf7oWaMIpcrjrJ+IOwb4dMd80vH+fzDNP/NnFZT9dYl/fpcuEZO/RdgzP5sPLCW6U6VlT4zBToYLVDnwqzzo/rEqgen50H6QoFWm2iySS0FmxYfB+rfNhdv54+49Kq3IEr24mh8XgGX6rYqpUQ9F1puhrCXwLfDG/zY5B2qmrdk7JLkI=
  on:
    all_branches: true
    distributions: sdist bdist_wheel
    repo: sgaynetdinov/py-vkontakte
    skip_cleanup: true
