language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements-dev.txt
script:
  - isort -c
  - pytest
deploy:
  provider: pypi
  user: 10349hndsmfa90sdhfbn230
  password:
    secure: qVRDcI/E9dZ8hTEt5pFG0ABK2Da+u6aEuQC7Z/0QP7vAK3ErwqtMukhwPEhL0dSein1F91IXVMuOpWNRzCf5mtESn9HKqrvL6Q1NjI2jGAnTCd9UvlOKrSTtGqhjjj8p7NF3hUCDJ4PDEK7eNhzfNprTtIHbT3tbzjnokOz8qnwQtacvEqAFQUEVCj5edNF1hosZVjBTIk4iG4cJ6Z5hYVkfkRyGRfBsjBDzsblRkYcpxemEBFdtri06RVxfODTPI3iNYhVUuPTpNKUzSFbJHHbS+NfvzDcE5XLW9MhkfNYz2BiWOwaUWbhy0n4i5DZTsyhE65uVpkkt/QkenspX0XofJz2n4oxBAiOa/dmT9Oa1Fe099Fh31lkKvCDSCmZZhObaULDOsQIBXB+CxmnNYtUC0wMk+oyjcjijqiHfoxjaIfpq+ql9GrIoRwMa0IDR+h6nZicDhPlvMkEx4PSlDQAh8UA9AZ5cCEwLZs2DkrSafH+YLPaMWomCMQcU01/JYAtt21d7HCg4BqSu9VJpAupDzns8Uq8loF+QBchMuL3mYAR7wsV7sCDTyiXwev6fYg5qSQdNrknzPcfYFduFqsMQtnnap6pqb8oHRM/uAvMfNKnyJ7Slicy8I4V07Do+znVH/6SJCj+93tt29WmB8Jed3EdIY49ZSfEQaFmXCqI=
  on:
    all_branches: true
    distributions: sdist bdist_wheel
    repo: sgaynetdinov/py-vkontakte
    skip_cleanup: true
