language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements-dev.txt
  - pip install codecov pytest-cov
after_success:
    - codecov
script:
  - isort -c
  - pytest
deploy:
  provider: pypi
  user: 10349hndsmfa90sdhfbn230
  password:
    secure: qZNyV96CU1Ry4u7SO60UM+d1/PeO68OQAN+HviNGmRkhiMB34TZRMQPpEmjo6zY4YQtVS1tM/AghzoGkdrsmUaT4AlaxHDRQ+lF4pflF9PBsVdu2VlGqTPbW/IrnxSpO4W5hFUZ13QI23HQuEhegp6G+Y65WR/8/7CgYYhgBH8h8zNTBm6Ef4nTCHs3hgJTNnnYPNwG11zUvzYvzgdAj/3dfVYPX1LtKD6T12aetuuRoV8QKNgb5LCJoBQ1te7VGxE7LP72PYi7dIJv9NU/wh4opzCvYwRtqndgTXIwyNnbbTYjRH29EDRyEHQL+BW2TAMe72ejxHnmwIdXZ1T/lbftKsa0qL38jIfF4a+MM4JDPMXiFOHD/JUvhL5YCygnXUe0I1RBfFpPdMqMqpYorx/KQZ4J1OqZpJg0KkXv/4o8INatzHnkDkIHnmIwJ58eQgi9quU4XinWT6rDbWACdS0vWDh8VeA3ZNUJvZD1Jmw3EGU6CHYtXORZniyWQBBperF+ewzJ/fle0OGbfgVq9BP907l5d06k4z0OVHpRJYLaREAizcwRfTvEkAPBqB38MMrR4bXOmockoZCwgjk73ahddUHzbksqHP7U3lrxSsMylAqmt4kRuSGAWs04+CTcZ3MqskRiCUpcDwuDQfF/ucoKEwaOJQMbPmKAQacm+Rxs=
  on:
    tags: true
    skip_cleanup: true
    skip_existing: true
    distributions: "sdist bdist_wheel"
    repo: sgaynetdinov/py-vkontakte
