language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r requirements-dev.txt
script:
  - isort -c
  - pytest

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true